spring.application.name=Game Rental - ${spring.profiles.active:all}
spring.datasource.url=jdbc:h2:./database;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

axon.axonserver.enabled=true
axon.axonserver.context=game-rental

# Axoniq Platform connection
# Access token workspace "workflow-gameday-steven" / environment "Development".
# Switch environment in the top-left to fill another. You can manage tokens under settings -> Access tokens.
#axoniq.platform.credentials=91722ad3-0:968331d2ebda477ba032ab02bda30fb1
#axoniq.platform.host=inspector.dev.axoniq.net