spring.application.name=Game Rental - ${spring.profiles.active:all}

spring.datasource.url=jdbc:h2:./database;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

axon.eventhandling.processors.game-catalog.mode=pooled
axon.eventhandling.processors.game-catalog.thread-count=4
axon.eventhandling.processors.game-catalog.batch-size=50
axon.eventhandling.processors.game-catalog.token-claim-interval=2500

axon.eventhandling.processors.reservations.mode=pooled
axon.eventhandling.processors.reservations.thread-count=4
axon.eventhandling.processors.reservations.batch-size=25
axon.eventhandling.processors.reservations.token-claim-interval=4000

axon.eventhandling.processors.stuck-segment-demo.mode=pooled
axon.eventhandling.processors.stuck-segment-demo.initial-segment-count=4
axon.eventhandling.processors.stuck-segment-demo.thread-count=4
axon.eventhandling.processors.stuck-segment-demo.batch-size=1
axon.eventhandling.processors.stuck-segment-demo.token-claim-interval=2500
axon.eventhandling.processors.stuck-segment-demo.sequencing-policy=stuckSegmentSequencingPolicy
