spring.application.name=Game Rental Application - ${spring.profiles.active}

spring.datasource.url=jdbc:h2:./database;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=username
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

axon.axonserver.enabled=false

axon.eventhandling.processors.game-catalog.mode=pooled
axon.eventhandling.processors.game-catalog.thread-count=16
axon.eventhandling.processors.game-catalog.initial-segment-count=16
axon.eventhandling.processors.game-catalog.batch-size=1
